# Generated by Django 4.2.3 on 2023-08-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
